apiVersion: apps/v1
kind: Deployment
metadata:
  name: evershop-app-dep
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: ever-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ever-app
  template:
    metadata:
      name: evershop-pod
      labels:
        app: ever-app
    spec:
      containers:
        - name: evershop-app-con
          image: sairathod/evershop-app:v1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: ever-config


---
apiVersion: v1
kind: Service
metadata:
  name: evershop-app-ser
  labels:
    app: ever-app
spec:
  type: NodePort
  selector:
    app: ever-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000

