apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: evershop-vpa
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: evershop-app-state
  updatePolicy:
    updateMode: "Auto"  

